#!/bin/sh

# $HOME/.xinitrc

### Start Xserver & Window Manager in a DBus session:
PID_XSESSION=$$

wmaker --no-dock --no-clip --static &
notify-send "PiSi Desktop is loading..."
sleep 1
openapp SimpleAgenda &
sleep 2
exec dbus-launch --sh-syntax --exit-with-session openapp GWorkspace

kill $PID_XSESSION

############ INFO ###############################################
### DMPS and blanking issues on RPI machine
### are fixed (xset) within
### $HOME/.config/openbox/autostart
### Not here!
#################################################################
### Setting GNUstep environment
### This is done with .profile, not here.
#################################################################
