#!/bin/sh

# $HOME/.xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

### Start Xserver & Window Manager:
exec wmaker

############ INFO ###############################################
### DMPS and blanking issues on RPI machine
### are fixed (xset) within
### $HOME/GNUstep/Library/WindowMaker/autostart
### Not here!
#################################################################
### Setting GNUstep environment
### This is done with .profile, not here.
#################################################################
### Starting Apps within wmaker is done
### with session management...
### and thensaved in WMState ans WMWindowAttributes
### Not here.
#################################################################
