#!/bin/bash
#
# WindowMaker will wait until this script finishes, so if you run any
# commands that take long to execute (like a xterm), put a ``&'' in the
# end of the command line.
#
# This file must be executable.
#
xset m 20/10 4

### This is to prevent DMPS and blanking issues on RPI machine
xset -dpms
xset s off

### gdnc
gdomap -L GDNCServer || gdnc &

### compton: the -b arg means as a daemon like &
pgrep compton || compton -b

### Notifications
systemctl --user import-environment DISPLAY
pgrep dunst || dunst &
sleep 2 && /usr/local/bin/loading.sh &

### conky
pgrep conky || sleep 6 && conky -c ~/.config/pisin/conky.conf &
PREFIX=$(echo ${LANG%.UTF-8} | awk -F'_' '{print $1}')
