#!/bin/bash
#
# WindowMaker will wait until this script finishes, so if you run any
# commands that take long to execute (like a xterm), put a ``&'' in the
# end of the command line.
#
# This file must be executable.
#
xset m 20/10 4

### This is to prevent DMPS and blanking issues on RPI machine
xset -dpms
xset s off

### gdnc
gdomap -L GDNCServer || gdnc &

### compton: the -b arg means as a daemon like &
pgrep compton || compton -b

### Notifications
systemctl --user import-environment DISPLAY
pgrep dunst || dunst &
dunstify "PiSiN Desktop is loading..."

### conky
pgrep conky || sleep 8 && conky -c ~/.config/pisin/conky.conf &

### Updater notification
sleep 60 && /usr/local/bin/Updater.sh -d &
